In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import requests

In [2]:
symbol = "NSE_INDEX%7CNifty%2050"

# nifty 50 historical data params
interval = "days"
frequency = "1"
to_date = "2025-12-16"
from_date = "2025-11-11"

In [3]:
# for nifty 50 historical data
url = f"https://api.upstox.com/v3/historical-candle/{symbol}/{interval}/{frequency}/{to_date}/{from_date}"
response = requests.get(url)
if response.status_code == 200:
    print(response.json())
else:
    print(f"Error: {response.status_code} - {response.text}")

{'status': 'success', 'data': {'candles': [['2025-12-16T00:00:00+05:30', 25951.5, 25980.75, 25834.35, 25860.1, 0, 0], ['2025-12-15T00:00:00+05:30', 25930.05, 26047.15, 25904.75, 26027.3, 0, 0], ['2025-12-12T00:00:00+05:30', 25971.2, 26057.6, 25938.45, 26046.95, 0, 0], ['2025-12-11T00:00:00+05:30', 25771.4, 25922.8, 25693.25, 25898.55, 0, 0], ['2025-12-10T00:00:00+05:30', 25864.05, 25947.65, 25734.55, 25758.0, 0, 0], ['2025-12-09T00:00:00+05:30', 25867.1, 25923.65, 25728.0, 25839.65, 0, 0], ['2025-12-08T00:00:00+05:30', 26159.8, 26178.7, 25892.25, 25960.55, 0, 0], ['2025-12-05T00:00:00+05:30', 25999.8, 26202.6, 25985.35, 26186.45, 0, 0], ['2025-12-04T00:00:00+05:30', 25981.85, 26098.25, 25938.95, 26033.75, 0, 0], ['2025-12-03T00:00:00+05:30', 26004.9, 26066.45, 25891.0, 25986.0, 0, 0], ['2025-12-02T00:00:00+05:30', 26087.95, 26154.6, 25997.85, 26032.2, 0, 0], ['2025-12-01T00:00:00+05:30', 26325.8, 26325.8, 26124.2, 26175.75, 0, 0], ['2025-11-28T00:00:00+05:30', 26237.45, 26280.75, 26172.4, 26202.95, 0, 0], ['2025-11-27T00:00:00+05:30', 26261.25, 26310.45, 26141.9, 26215.55, 0, 0], ['2025-11-26T00:00:00+05:30', 25842.95, 26215.15, 25842.95, 26205.3, 0, 0], ['2025-11-25T00:00:00+05:30', 25998.5, 26032.6, 25857.5, 25884.8, 0, 0], ['2025-11-24T00:00:00+05:30', 26122.8, 26142.8, 25912.15, 25959.5, 0, 0], ['2025-11-21T00:00:00+05:30', 26109.55, 26179.2, 26052.2, 26068.15, 0, 0], ['2025-11-20T00:00:00+05:30', 26132.1, 26246.65, 26063.2, 26192.15, 0, 0], ['2025-11-19T00:00:00+05:30', 25918.1, 26074.65, 25856.2, 26052.65, 0, 0], ['2025-11-18T00:00:00+05:30', 26021.8, 26029.85, 25876.5, 25910.05, 0, 0], ['2025-11-17T00:00:00+05:30', 25948.2, 26024.2, 25906.35, 26013.45, 0, 0], ['2025-11-14T00:00:00+05:30', 25767.9, 25940.2, 25740.8, 25910.05, 0, 0], ['2025-11-13T00:00:00+05:30', 25906.1, 26010.7, 25808.4, 25879.15, 0, 0], ['2025-11-12T00:00:00+05:30', 25834.3, 25934.55, 25781.15, 25875.8, 0, 0], ['2025-11-11T00:00:00+05:30', 25617.0, 25715.8, 25449.25, 25694.95, 0, 0]]}}

In [4]:
nifty_df = pd.DataFrame()
nifty_df['Date'] = pd.to_datetime([item[0].split("T")[0] for item in response.json()['data']['candles']])
nifty_df['Close'] = [item[4] for item in response.json()['data']['candles']]
nifty_df['Open'] = [item[1] for item in response.json()['data']['candles']]
nifty_df['High'] = [item[2] for item in response.json()['data']['candles']]
nifty_df['Low'] = [item[3] for item in response.json()['data']['candles']]
nifty_df.set_index('Date', inplace=True)
nifty_df.sort_index(inplace=True)
nifty_df['logReturn'] = np.log(nifty_df['Close']/nifty_df['Close'].shift(1))
nifty_df['pctReturn'] = nifty_df['Close'].pct_change()
nifty_df

               Close      Open      High       Low  logReturn  pctReturn
Date
2025-11-11  25694.95  25617.00  25715.80  25449.25        NaN        NaN
2025-11-12  25875.80  25834.30  25934.55  25781.15   0.007014   0.007038
2025-11-13  25879.15  25906.10  26010.70  25808.40   0.000129   0.000129
2025-11-14  25910.05  25767.90  25940.20  25740.80   0.001193   0.001194
2025-11-17  26013.45  25948.20  26024.20  25906.35   0.003983   0.003991
2025-11-18  25910.05  26021.80  26029.85  25876.50  -0.003983  -0.003975
2025-11-19  26052.65  25918.10  26074.65  25856.20   0.005489   0.005504
2025-11-20  26192.15  26132.10  26246.65  26063.20   0.005340   0.005355
2025-11-21  26068.15  26109.55  26179.20  26052.20  -0.004745  -0.004734
2025-11-24  25959.50  26122.80  26142.80  25912.15  -0.004177  -0.004168
2025-11-25  25884.80  25998.50  26032.60  25857.50  -0.002882  -0.002878
2025-11-26  26205.30  25842.95  26215.15  25842.95   0.012306   0.012382
2025-11-27  26215.55  26261.25  26310.45  26141.90   0.000391   0.000391
2025-11-28  26202.95  26237.45  26280.75  26172.40  -0.000481  -0.000481
2025-12-01  26175.75  26325.80  26325.80  26124.20  -0.001039  -0.001038
2025-12-02  26032.20  26087.95  26154.60  25997.85  -0.005499  -0.005484
2025-12-03  25986.00  26004.90  26066.45  25891.00  -0.001776  -0.001775
2025-12-04  26033.75  25981.85  26098.25  25938.95   0.001836   0.001838
2025-12-05  26186.45  25999.80  26202.60  25985.35   0.005848   0.005865
2025-12-08  25960.55  26159.80  26178.70  25892.25  -0.008664  -0.008627
2025-12-09  25839.65  25867.10  25923.65  25728.00  -0.004668  -0.004657
2025-12-10  25758.00  25864.05  25947.65  25734.55  -0.003165  -0.003160
2025-12-11  25898.55  25771.40  25922.80  25693.25   0.005442   0.005457
2025-12-12  26046.95  25971.20  26057.60  25938.45   0.005714   0.005730
2025-12-15  26027.30  25930.05  26047.15  25904.75  -0.000755  -0.000754
2025-12-16  25860.10  25951.50  25980.75  25834.35  -0.006445  -0.006424

In [5]:
nifty_df.to_csv('data/nifty_50_historical_data.csv')

In [6]:
options_chain = pd.read_csv("data/Quote-Derivative-NIFTY-22-06-2025-22-12-2025.csv")
options_chain.replace('-', np.nan, inplace=True)
options_chain.dropna(inplace=True)
options_chain['Date'] = pd.to_datetime(options_chain['Date'])
options_chain['Expiry Date'] = pd.to_datetime(options_chain['Expiry Date'])
options_chain.set_index('Date', inplace=True)
options_chain.sort_index(inplace=True)
options_chain

,Expiry Date,Option Type,Strike Price,Open Price,High Price,Low Price,Close Price,Last Price,Settlement Price,Volume,Value (₹ Lakhs),Premium Value (₹ Lakhs),Open Interest,Change in OI
Date,,,,,,,,,,,,,,
2025-11-12,2025-12-16,PE,"26,500.00",562.10,564.00,530.10,533.05,533.05,678.30,900,"2,43,42,540.00","4,92,540.00",450,450
2025-11-12,2025-12-16,CE,"25,900.00",431.00,473.65,407.60,468.90,468.90,445.75,3225,"8,49,13,192.50","13,85,692.50",1650,1650
2025-11-12,2025-12-16,CE,"27,450.00",51.00,51.00,13.00,21.00,20.00,21.00,1575,"4,32,69,191.25","35,441.25",675,675
2025-11-12,2025-12-16,CE,"26,200.00",252.05,303.20,252.05,286.75,286.75,286.75,1125,"2,97,94,035.00","3,19,035.00",750,750
2025-11-12,2025-12-16,CE,"25,800.00",488.00,541.65,468.90,505.50,504.80,505.50,3150,"8,28,46,500.00","15,76,500.00",975,975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-16,2025-12-16,PE,"24,850.00",0.95,1.00,0.05,0.10,0.05,"25,860.10",6546225,"1,62,67,71,36,168.75","34,44,918.75",565050,-216975
2025-12-16,2025-12-16,CE,"24,550.00","1,352.00","1,356.00","1,342.00","1,342.00","1,342.00","25,860.10",1275,"3,30,22,950.00","17,21,700.00",225,-1050
2025-12-16,2025-12-16,PE,"24,250.00",0.75,0.80,0.05,0.10,0.05,"25,860.10",1963650,"47,61,93,10,635.00","7,98,135.00",158625,-82650
2025-12-16,2025-12-16,CE,"25,400.00",531.00,546.55,456.35,471.05,460.50,"25,860.10",165825,"4,29,40,41,750.00","8,20,86,750.00",32775,-22875
2025-12-16,2025-12-16,CE,"26,800.00",0.65,0.95,0.05,0.05,0.05,"25,860.10",45926475,"12,30,85,86,88,278.75","2,91,58,278.75",3339750,-1683600

In [7]:
options_chain.to_csv('data/nifty_50_options_chain.csv')